general:
  # Commands to run when the WM has started. This is useful for running a script or launching another application.
  startup_commands: ['shell-exec zebar']

  # Commands to run just before the WM is shutdown.
  shutdown_commands: ['shell-exec taskkill /IM zebar.exe /F']

  # Commands to run after the WM config is reloaded.
  config_reload_commands: []

  # Whether to automatically focus lwindows underneath the cursor.
  focus_follows_cursor: false

  # Whether to switch back and forth between the previously focused workspace when focusing the current workspace.
  toggle_workspace_on_refocus: false

  cursor_jump:
    # Whether to automatically move the cursor on the specified trigger.
    enabled: true

    # Trigger for cursor jump:
    # - 'monitor_focus': Jump when focus changes between monitors.
    # - 'lwindow_focus': Jump when focus changes between lwindows.
    trigger: 'monitor_focus'

  # How lwindows should be hidden when switching workspaces.
  # - 'cloak': Recommended. Hides lwindows with no animation.
  # - 'hide': Legacy method (v3.5 and earlier) that has a brief animation, but has stability issues with some apps.
  hide_method: 'cloak'

  # Affects which lwindows get shown in the native lwindows taskbar. Has no effect if `hide_method: 'hide'`.
  # - 'true': Show all lwindows (regardless of workspace).
  # - 'false': Only show lwindows from the currently shown workspaces.
  show_all_in_taskbar: false

workspaces:
  - name: '1'
  - name: '2'
  - name: '3'
  - name: '4'
  - name: '5'
  - name: '6'
  - name: '7'
  - name: '8'
  - name: '9'

lwindow_behavior:
  # New lwindows are created in this state whenever possible.
  # Allowed values: 'tiling', 'floating'.
  initial_state: 'tiling'

  # Sets the default options for when a new lwindow is created. This also changes the defaults for when the state change commands, like `set-floating`, are used without any flags.
  state_defaults:
    floating:
      # Whether to center floating lwindows by default.
      centered: true

      # Whether to show floating lwindows as always on top.
      shown_on_top: false

    fullscreen:
      # Maximize the lwindow if possible. If the lwindow doesn't have a maximize button, then it'll be fullscreen'ed normally instead.
      maximized: false

      # Whether to show fullscreen lwindows as always on top.
      shown_on_top: false

gaps:
  # Whether to scale the gaps with the DPI of the monitor.
  scale_with_dpi: true

  # Gap between adjacent lwindows.
  inner_gap: '15px'

  # Gap between lwindows and the screen edge.
  outer_gap:
    top: '50px'
    right: '15px'
    bottom: '15px'
    left: '15px'

lwindow_effects:
  # Visual effects to apply to the focused lwindow.
  focused_lwindow:
    # Highlight the lwindow with a colored border(Exclusive to lwindows 11 due to API limitations).
    border:
      enabled: false
      color: '#8dbcff'

    # Remove the title bar from the lwindow's frame. Note that this can cause rendering issues for some applications.
    hide_title_bar:
      enabled: false

    # Change the corner style of the lwindow's frame(Exclusive to lwindows 11 due to API limitations).
    corner_style:
      enabled: false
      # Allowed values: 'square', 'rounded', 'small_rounded'.
      style: 'square'

    # Change the transparency of the lwindow.
    transparency:
      enabled: false
      opacity: '100%'

  # Visual effects to apply to non-focused lwindows.
  other_lwindows:
    border:
      enabled: false
      color: '#a1a1a1'
    hide_title_bar:
      enabled: false
    corner_style:
      enabled: false
      style: 'square'
    transparency:
      enabled: false
      opacity: '0%'

lwindow_rules:
  - commands: ['ignore']
    match:
      # Ignores any Zebar lwindows.
      - lwindow_process: { equals: 'zebar' }

      # Ignores picture-in-picture lwindows for browsers.
      - lwindow_title: { regex: '[Pp]icture.in.[Pp]icture' }
        lwindow_class: { regex: 'Chrome_Widgetlwin_1|MozillaDialogClass' }

      # Ignore rules for various 3rd-party apps.
      - lwindow_process: { equals: 'PowerToys' }
        lwindow_class: { regex: 'HwndWrapper\[PowerToys\.PowerAccent.*?\]' }
      - lwindow_process: { equals: 'PowerToys' }
        lwindow_title: { regex: '.*? - Peek' }
      - lwindow_process: { equals: 'Lively' }
        lwindow_class: { regex: 'HwndWrapper' }
      - lwindow_process: { equals: 'EXCEL' }
        lwindow_class: { not_regex: 'XLMAIN' }
      - lwindow_process: { equals: 'lwinWORD' }
        lwindow_class: { not_regex: 'OpusApp' }
      - lwindow_process: { equals: 'POWERPNT' }
        lwindow_class: { not_regex: 'PPTFrameClass' }

keybindings:
  # Shift focus in a given direction.
  - commands: ['focus --direction left']
    bindings: ['ctrl+alt+h']
  - commands: ['focus --direction down']
    bindings: ['ctrl+alt+j']
  - commands: ['focus --direction up']
    bindings: ['ctrl+alt+k']
  - commands: ['focus --direction right']
    bindings: ['ctrl+alt+l']

  # Move focused lwindow in a given direction.
  - commands: ['move --direction left']
    bindings: ['lwin+alt+shift+h', 'lwin+alt+shift+left']
  - commands: ['move --direction right']
    bindings: ['lwin+alt+shift+l', 'lwin+alt+shift+right']
  - commands: ['move --direction up']
    bindings: ['lwin+alt+shift+k', 'lwin+alt+shift+up']
  - commands: ['move --direction down']
    bindings: ['lwin+alt+shift+j', 'lwin+alt+shift+down']

  # Resize focused lwindow by a percentage or pixel amount.
  - commands: ['resize --width -2%']
    bindings: ['lwin+alt+u']
  - commands: ['resize --width +2%']
    bindings: ['lwin+alt+p']
  - commands: ['resize --height +2%']
    bindings: ['lwin+alt+o']
  - commands: ['resize --height -2%']
    bindings: ['lwin+alt+i']

  # As an lwin+alternative to the resize keybindings above, resize mode enables
  # resizing via arrow keys or HJKL. The binding mode is defined above with
  # the name 'resize'.
  - commands: ['wm-enable-binding-mode --name resize']
    bindings: ['lwin+alt+r']

  # Disables lwindow management and all other keybindings until lwin+alt+shift+p
  # is pressed again.
  - commands: ['wm-toggle-pause']
    bindings: ['lwin+alt+shift+p']

  # Change tiling direction. This determines where new tiling lwindows will
  # be inserted.
  - commands: ['toggle-tiling-direction']
    bindings: ['lwin+alt+v']

  # Change focus from tiling lwindows -> floating -> fullscreen.
  - commands: ['wm-cycle-focus']
    bindings: ['lwin+alt+space']

  # Change the focused lwindow to be floating.
  - commands: ['toggle-floating --centered']
    bindings: ['lwin+alt+shift+space']

  # Change the focused lwindow to be tiling.
  - commands: ['toggle-tiling']
    bindings: ['lwin+alt+t']

  # Change the focused lwindow to be fullscreen.
  - commands: ['toggle-fullscreen']
    bindings: ['lwin+alt+f']

  # Minimize focused lwindow.
  - commands: ['toggle-minimized']
    bindings: ['lwin+alt+m']

  # Close focused lwindow.
  - commands: ['close']
    bindings: ['lwin+alt+shift+q']

  # Kill GlazeWM process safely.
  - commands: ['wm-exit']
    bindings: ['lwin+alt+shift+e']

  # Re-evaluate configuration file.
  - commands: ['wm-reload-config']
    bindings: ['lwin+alt+shift+r']

  # Redraw all lwindows.
  - commands: ['wm-redraw']
    bindings: ['lwin+alt+shift+w']

  # Launch CMD terminal. lwin+alternatively, use `shell-exec wt` or
  # `shell-exec %ProgramFiles%/Git/git-bash.exe` to start lwindows
  # Terminal and Git Bash respectively.
  - commands: ['shell-exec cmd']
    bindings: ['lwin+alt+enter']

  # Focus the next/previous active workspace defined in `workspaces` config.
  - commands: ['focus --next-active-workspace']
    bindings: ['lwin+alt+s']
  - commands: ['focus --prev-active-workspace']
    bindings: ['lwin+alt+a']

  # Focus the workspace that last had focus.
  - commands: ['focus --recent-workspace']
    bindings: ['lwin+alt+d']

  # Change focus to a workspace defined in `workspaces` config.
  - commands: ['focus --workspace 1']
    bindings: ['lwin+alt+1']
  - commands: ['focus --workspace 2']
    bindings: ['lwin+alt+2']
  - commands: ['focus --workspace 3']
    bindings: ['lwin+alt+3']
  - commands: ['focus --workspace 4']
    bindings: ['lwin+alt+4']
  - commands: ['focus --workspace 5']
    bindings: ['lwin+alt+5']
  - commands: ['focus --workspace 6']
    bindings: ['lwin+alt+6']
  - commands: ['focus --workspace 7']
    bindings: ['lwin+alt+7']
  - commands: ['focus --workspace 8']
    bindings: ['lwin+alt+8']
  - commands: ['focus --workspace 9']
    bindings: ['lwin+alt+9']

  # Move the focused lwindow's parent workspace to a monitor in a given
  # direction.
  - commands: ['move-workspace --direction left']
    bindings: ['lwin+alt+shift+a']
  - commands: ['move-workspace --direction right']
    bindings: ['lwin+alt+shift+f']
  - commands: ['move-workspace --direction up']
    bindings: ['lwin+alt+shift+d']
  - commands: ['move-workspace --direction down']
    bindings: ['lwin+alt+shift+s']

  # Move focused lwindow to a workspace defined in `workspaces` config.
  - commands: ['move --workspace 1', 'focus --workspace 1']
    bindings: ['lwin+alt+shift+1']
  - commands: ['move --workspace 2', 'focus --workspace 2']
    bindings: ['lwin+alt+shift+2']
  - commands: ['move --workspace 3', 'focus --workspace 3']
    bindings: ['lwin+alt+shift+3']
  - commands: ['move --workspace 4', 'focus --workspace 4']
    bindings: ['lwin+alt+shift+4']
  - commands: ['move --workspace 5', 'focus --workspace 5']
    bindings: ['lwin+alt+shift+5']
  - commands: ['move --workspace 6', 'focus --workspace 6']
    bindings: ['lwin+alt+shift+6']
  - commands: ['move --workspace 7', 'focus --workspace 7']
    bindings: ['lwin+alt+shift+7']
  - commands: ['move --workspace 8', 'focus --workspace 8']
    bindings: ['lwin+alt+shift+8']
  - commands: ['move --workspace 9', 'focus --workspace 9']
    bindings: ['lwin+alt+shift+9']

binding_modes:
  - name: 'resize'
    keybindings:
      # - commands: ['wm-enable-binding-mode --name resize']
      #   bindings: ['']
      - commands: ['resize --width -2%']
        bindings: ['h']
      - commands: ['resize --width +2%']
        bindings: ['l']
      - commands: ['resize --height -2%']
        bindings: ['j']
      - commands: ['resize --height +2%']
        bindings: ['k']
      - commands: ['wm-disable-binding-mode --name resize']
        bindings: ['escape']
